1: What are the three longest trips on rainy days?

WITH
	short_dates
AS (
SELECT
	substring(start_date from 1 for 10) short,
	duration,
	trip_id
FROM
	trips)

SELECT
	short_dates.short,
	short_dates.trip_id,
	short_dates.duration,
	weather.events,
	weather.date
FROM
	short_dates
JOIN
	weather
ON
	short_dates.short = weather.date
WHERE
	events LIKE 'Rain'
ORDER BY
	duration
DESC

2: Which station is full most often?

SELECT
status.station_id,
stations.name,

COUNT(CASE WHEN docks_available=0 then 1 END) empty_count

FROM status

JOIN stations

on stations.station_id = status.station_id

GROUP BY 1,2

ORDER BY empty_count DESC

3: Return a list of stations with a count of number of trips starting at that station but ordered by dock count.

SELECT
start_station,
dockcount,

COUNT(*)

FROM trips

JOIN stations

ON stations.name=trips.start_station

GROUP BY 1, 2

ORDER BY 2 DESC

4: (Challenge) What's the length of the longest trip for each day it rains anywhere?

WITH rainy as 
(
SELECT 

DATE(date) weather_date

From weather

WHERE events = 'Rain'

GROUP BY 1
),

rain_trips as (
SELECT

trip_id,

duration,

DATE(trips.start_date) rain_trips_date

FROM trips

JOIN rainy

on rainy.weather_date = DATE(trips.start_date)

ORDER BY duration DESC
)

SELECT 

rain_trips_date,

max(duration) max_duration

from rain_trips

GROUP BY 1

ORDER BY max_duration DESC